### ISSUE TITLE
How to generate X9 files from scratch?

### ISSUE THREAD

**Issue by leordev** [TheLastCheck/tlc.open.java#6]
Hello Jerry! First of all I would like to congrats you a lot for create this open source library.
It's exactly my business requirements!

I have all the checks data and tifs images in our software, now we just need to generate the X9 binary file. As I did not find the docs in the wiki, I tried to generate the X9 using the following code:

```
            // Header File
            X937FileHeaderRecordImpl headerRecord = new X937FileHeaderRecordImpl();
            headerRecord.standardLevel("03");
            headerRecord.testFileIndicator("P");
            headerRecord.immediateDestinationRoutingNumber("123456789");
            headerRecord.immediateOriginRoutingNumber("123456789");
            headerRecord.fileCreationDate(DateTime.now().toDate());
            headerRecord.fileCreationTime(DateTime.now().toDate());
            headerRecord.resendIndicator("N");
            headerRecord.immediateDestinationName("Bank of America");
            headerRecord.immediateOriginName("Bank of Leo");
            headerRecord.fileIDModifier("0");
            headerRecord.countryCode("  ");
            headerRecord.userField("    ");
            headerRecord.reserved(" ");

            // Cash Letter Header
            X937CashLetterHeaderRecordImpl cashLetterHeaderRecord = new X937CashLetterHeaderRecordImpl();
            cashLetterHeaderRecord.collectionTypeIndicator("01");
            cashLetterHeaderRecord.destinationRoutingNumber("042000314");
            cashLetterHeaderRecord.ECEInstitutionRoutingNumber("123456789");
            cashLetterHeaderRecord.cashLetterBusinessDate(DateTime.now().toDate());
            cashLetterHeaderRecord.cashLetterCreationDate(DateTime.now().toDate());
            cashLetterHeaderRecord.cashLetterCreationTime(DateTime.now().toDate());
            cashLetterHeaderRecord.cashLetterRecordTypeIndicator("I");
            cashLetterHeaderRecord.cashLetterDocumentationTypeIndicator("G");
            cashLetterHeaderRecord.cashLetterID("00109301");
            cashLetterHeaderRecord.originatorContactName("Leo");
            cashLetterHeaderRecord.originatorContactName("17862122405");
            cashLetterHeaderRecord.fedWorkType(" ");
            cashLetterHeaderRecord.userField("  ");
            cashLetterHeaderRecord.reserved(" ");

            // Bundle Header
            X937BundleHeaderRecordImpl bundleHeaderRecord = new X937BundleHeaderRecordImpl();
            bundleHeaderRecord.collectionTypeIndicator("01");
            bundleHeaderRecord.destinationRoutingNumber("123456789");
            bundleHeaderRecord.ECEInstitutionRoutingNumber("123456789");
            bundleHeaderRecord.bundleBusinessDate(DateTime.now().toDate());
            bundleHeaderRecord.bundleCreationDate(DateTime.now().toDate());
            bundleHeaderRecord.bundleID("0000000001");
            bundleHeaderRecord.bundleSequenceNumber("0001");
            bundleHeaderRecord.cycleNumber("01");
            bundleHeaderRecord.returnLocationRoutingNumber("123456789");
            bundleHeaderRecord.userField("     ");
            bundleHeaderRecord.reserved("            ");

            // Check Detail
            X937CheckDetailRecordImpl checkDetailRecord = new X937CheckDetailRecordImpl();
            checkDetailRecord.auxiliaryOnUs("               ");
            checkDetailRecord.externalProcessingCode(" ");
            checkDetailRecord.payorBankRoutingNumber("987654321");
            checkDetailRecord.onUs("0000000001/000000042");
            checkDetailRecord.itemAmount("0000010000");
            checkDetailRecord.ECEInstitutionItemSequenceNumber("000000000100045");
            checkDetailRecord.documentationTypeIndicator("G");
            checkDetailRecord.returnAcceptanceIndicator("0");
            checkDetailRecord.MICRValidIndicator("1");
            checkDetailRecord.BOFDIndicator("Y");
            checkDetailRecord.checkDetailRecordAddendumCount("01");
            checkDetailRecord.correctionIndicator(" ");
            checkDetailRecord.archiveTypeIndicator(" ");

            // Check Addendum A
            X937CheckDetailAddendumARecordImpl checkDetailAddendumARecord =
                    new X937CheckDetailAddendumARecordImpl();
            checkDetailAddendumARecord.checkDetailAddendumARecordNumber("1");
            checkDetailAddendumARecord.BOFDRoutingNumber("123456789");
            checkDetailAddendumARecord.BOFDBusinessDate(DateTime.now().toDate());
            checkDetailAddendumARecord.BOFDItemSequenceNumber("000000000000001");
            checkDetailAddendumARecord.depositAccountNumberAtBOFD("                  ");
            checkDetailAddendumARecord.BOFDDepositBranch("     ");
            checkDetailAddendumARecord.payeeName("               ");
            checkDetailAddendumARecord.truncationIndicator("Y");
            checkDetailAddendumARecord.BOFDConversionIndicator(" ");
            checkDetailAddendumARecord.BOFDCorrectionIndicator(" ");
            checkDetailAddendumARecord.userField(" ");
            checkDetailAddendumARecord.reserved("   ");

            // Image View Detail - Front
            File checkFrontImage = new File(checkImagesPath + "/2016-05-13/547776/3322795-front.tif");
            X937ImageViewDetailRecordImpl frontImageViewDetailRecord = new X937ImageViewDetailRecordImpl();
            frontImageViewDetailRecord.imageIndicator("1");
            frontImageViewDetailRecord.imageCreatorRoutingNumber("123456789");
            frontImageViewDetailRecord.imageCreatorDate(DateTime.now().toDate());
            frontImageViewDetailRecord.imageViewFormatIndicator("00");
            frontImageViewDetailRecord.imageViewCompressionAlgorithmIdentifier("00");
            frontImageViewDetailRecord.imageViewDataSize((int) checkFrontImage.length());
            frontImageViewDetailRecord.viewSideIndicator("0");
            frontImageViewDetailRecord.viewDescriptor("00");
            frontImageViewDetailRecord.digitalSignatureIndicator("0");
            frontImageViewDetailRecord.digitalSignatureMethod("  ");
            frontImageViewDetailRecord.securityKeySize("     ");
            frontImageViewDetailRecord.startOfProtectedData("       ");
            frontImageViewDetailRecord.lengthofProtectedData("       ");
            frontImageViewDetailRecord.imageRecreateIndicator(" ");
            frontImageViewDetailRecord.userField("        ");
            frontImageViewDetailRecord.imageTiffVarianceIndicator(" ");
            frontImageViewDetailRecord.overrideIndicator(" ");
            frontImageViewDetailRecord.reserved("             ");

            // Image View Data - Front
            X937ImageViewDataRecordImpl frontImageViewDataRecord = new X937ImageViewDataRecordImpl();
            frontImageViewDataRecord.ECEInstitutionRoutingNumber("123456789");
            frontImageViewDataRecord.bundleBusinessDate(DateTime.now().toDate());
            frontImageViewDataRecord.cycleNumber("12");
            frontImageViewDataRecord.ECEInstitutionItemSequenceNumber("000000000000001");
            frontImageViewDataRecord.securityOriginatorName("                ");
            frontImageViewDataRecord.securityAuthenticatorName("                ");
            frontImageViewDataRecord.securityKeyName("                ");
            frontImageViewDataRecord.clippingOrigin("0");
            frontImageViewDataRecord.clippingCoordinateH1("    ");
            frontImageViewDataRecord.clippingCoordinateH2("    ");
            frontImageViewDataRecord.clippingCoordinateV1("    ");
            frontImageViewDataRecord.clippingCoordinateV2("    ");
            frontImageViewDataRecord.lengthOfImageReferenceKey("0000"); // I've changed this method from private to public... is this correct?
            frontImageViewDataRecord.lengthOfDigitalSignature("00000"); // I've changed this method from private to public... is this correct?
            frontImageViewDataRecord.lengthOfImageData((int) checkFrontImage.length()); // I've changed this method from private to public... is this correct?
            // TODO: how-to write image?

            // Image View Detail - Rear
            File checkRearImage = new File(checkImagesPath + "/2016-05-13/547776/3322795-rear.tif");
            X937ImageViewDetailRecordImpl rearImageViewDetailRecord = new X937ImageViewDetailRecordImpl();
            rearImageViewDetailRecord.imageIndicator("1");
            rearImageViewDetailRecord.imageCreatorRoutingNumber("123456789");
            rearImageViewDetailRecord.imageCreatorDate(DateTime.now().toDate());
            rearImageViewDetailRecord.imageViewFormatIndicator("00");
            rearImageViewDetailRecord.imageViewCompressionAlgorithmIdentifier("00");
            rearImageViewDetailRecord.imageViewDataSize((int) checkRearImage.length());
            rearImageViewDetailRecord.viewSideIndicator("1");
            rearImageViewDetailRecord.viewDescriptor("00");
            rearImageViewDetailRecord.digitalSignatureIndicator("0");
            rearImageViewDetailRecord.digitalSignatureMethod("  ");
            rearImageViewDetailRecord.securityKeySize("     ");
            rearImageViewDetailRecord.startOfProtectedData("       ");
            rearImageViewDetailRecord.lengthofProtectedData("       ");
            rearImageViewDetailRecord.imageRecreateIndicator(" ");
            rearImageViewDetailRecord.userField("        ");
            rearImageViewDetailRecord.imageTiffVarianceIndicator(" ");
            rearImageViewDetailRecord.overrideIndicator(" ");
            rearImageViewDetailRecord.reserved("             ");

            // Image View Data - Rear
            X937ImageViewDataRecordImpl rearImageViewDataRecord = new X937ImageViewDataRecordImpl();
            rearImageViewDataRecord.ECEInstitutionRoutingNumber("123456789");
            rearImageViewDataRecord.bundleBusinessDate(DateTime.now().toDate());
            rearImageViewDataRecord.cycleNumber("12");
            rearImageViewDataRecord.ECEInstitutionItemSequenceNumber("000000000000001");
            rearImageViewDataRecord.securityOriginatorName("                ");
            rearImageViewDataRecord.securityAuthenticatorName("                ");
            rearImageViewDataRecord.securityKeyName("                ");
            rearImageViewDataRecord.clippingOrigin("0");
            rearImageViewDataRecord.clippingCoordinateH1("    ");
            rearImageViewDataRecord.clippingCoordinateH2("    ");
            rearImageViewDataRecord.clippingCoordinateV1("    ");
            rearImageViewDataRecord.clippingCoordinateV2("    ");
            rearImageViewDataRecord.lengthOfImageReferenceKey("0000"); // I've changed this method from private to public... is this correct?
            rearImageViewDataRecord.lengthOfDigitalSignature("00000"); // I've changed this method from private to public... is this correct?
            rearImageViewDataRecord.lengthOfImageData((int) checkRearImage.length()); // I've changed this method from private to public... is this correct?
            // TODO: how-to write image?

            // Bundle Control
            X937BundleControlRecordImpl bundleControlRecord = new X937BundleControlRecordImpl();
            bundleControlRecord.itemsWithinBundleCount("1");
            bundleControlRecord.bundleTotalAmount("000000010000");
            bundleControlRecord.MICRValidTotalAmount("000000010000");
            bundleControlRecord.imagesWithinBundleCount("00002");
            bundleControlRecord.userField("                    ");
            bundleControlRecord.reserved("                         ");

            // Cash Letter Control
            X937CashLetterControlRecordImpl cashLetterControlRecord = new X937CashLetterControlRecordImpl();
            cashLetterControlRecord.bundleCount("000001");
            cashLetterControlRecord.itemsWithinCashletterCount("00000001");
            cashLetterControlRecord.cashLetterTotalAmount("00000000010000");
            cashLetterControlRecord.imagesWithinCashLetterCount("000000002");
            cashLetterControlRecord.ECEInstitutionName("Leo LLC");
            cashLetterControlRecord.settlementDate("        ");
            cashLetterControlRecord.reserved("               ");

            // File Control
            X937FileControlRecordImpl fileControlRecord = new X937FileControlRecordImpl();
            fileControlRecord.cashLetterCount("000001");
            fileControlRecord.totalRecordCount("00000012");
            fileControlRecord.totalItemCount("00000001");
            fileControlRecord.fileTotalAmount("0000000000010000");
            fileControlRecord.immediateOriginContactName("Leo");
            fileControlRecord.immediateOriginContactPhoneNumber("7862122405");
            fileControlRecord.reserved("                ");

            OutputStream os = new FileOutputStream("test-no-image.937");
            X9OutputStreamRecordWriter out = new X9OutputStreamRecordWriter(os);
            out.write(headerRecord);
            out.write(cashLetterHeaderRecord);
            out.write(bundleHeaderRecord);
            out.write(checkDetailRecord);
            out.write(checkDetailAddendumARecord);
            out.write(frontImageViewDetailRecord);
            out.write(frontImageViewDataRecord);
            out.write(rearImageViewDetailRecord);
            out.write(rearImageViewDataRecord);
            out.write(bundleControlRecord);
            out.write(cashLetterControlRecord);
            out.write(fileControlRecord);
            out.close();
```

But I'm getting a issue, when the code reach this line: `frontImageViewDataRecord.securityKeyName("                ");`

I get an exception in the below context on the current value.put method:
![image](https://cloud.githubusercontent.com/assets/6147142/15628102/9f097e60-24c6-11e6-9575-1635c07e556d.png)

I see that the ByteBuffer has a limit of 80 and 68 + 16 overpass it.
And then I need to know how can I "upload" or set my current .tif in this record... 

Can you give me an idea if I'm doing the correct steps to create the X9 file?
Also I need to generate ASCII or EBCDIC depending of the bank, how can I setup this in the output stream writer?

Thank you very much, and congratulations for this awesome lib.

**Comment by leonardolr** [comment]
Oh I think that I discovered how to update the tif file, using the method imageData of the Record 52. It's fine... now I just need help with the above "limit" issue...

**Comment by jerrybowman** [comment]
Thanks for your query and yes, I do need to add usage documentation :-). It's on my list...

First, you should use the x9 record factory to create instances of the records. Here is an example to create a new record factory:

```
    private X9RecordFactory buildX9RecordFactory() {
        X9RecordFactoryStrategy strategy = new DefaultX9RecordFactoryStrategy();
        return strategy.factory(X9RecordFactoryStrategy.X937_STANDARD_DSTU);
    }
```
The record factory knows about building the correct lengths for the various records, so the 52 record buffer will be big enough.

If you need to use a different encoding for the output file than the default of EBCDIC, you specify the value when you create the factory. For example to create a ASCII output file:

```
    private X9RecordFactory buildX9RecordFactory() {
        X9RecordFactoryStrategy strategy = new DefaultX9RecordFactoryStrategy();
        return strategy.factory(
            X9RecordFactoryStrategy.X937_STANDARD_DSTU, X9Record.ENCODING_ASCII);
    }
```
To make a generic build method, you could pass in the proper encoding where you determine that from some configuration option:
```
        X9RecordFactory factory;
        if (option.equals("EBCDIC")) {
            factory = buildX9RecordFactory(X9Record.ENCODING_EBCDIC);
        } else {
            factory = buildX9RecordFactory(X9Record.ENCODING_ASCII);
        }
    .
    .
    private X9RecordFactory buildX9RecordFactory(String encoding) {
        X9RecordFactoryStrategy strategy = new DefaultX9RecordFactoryStrategy();
        return strategy.factory(X9RecordFactoryStrategy.X937_STANDARD_DSTU, encoding) ;
    }
```
Also, since you are using the factory, you just work with the interfaces for the record, not the Impls. 
```
        X9RecordFactory factory = buildX9RecordFactory();
        Record x9Record = factory.newX9Record(X9Record.TYPE_FILE_HEADER);
        X937FileHeaderRecord fileHeaderRecord = (X937FileHeaderRecord) x9Record;
```
Of course, you can do the previous new header with one line instead of two.
```
        X9RecordFactory factory = buildX9RecordFactory();
        X937FileHeaderRecord fileHeaderRecord = 
            (X937FileHeaderRecord) factory.newX9Record(X9Record.TYPE_FILE_HEADER);
```
Now you are just working with the interfaces.

As for the 52 record, you do not need to make the set for the image length public. When you set the image, it will automatically calculate the length and set it. It will also expand or shrink the current 52 record buffer size based on the length of the image. The same is true for the other variable length fields. You do not need to initialize them to zero. The factory will do that for you by setting the data values for the imageReferenceKey and digitalSignature to empty values, which will set the length fields to 0.

The image must be wrapped in a ByteArray instance. So if you have read the image into an byte[] array, Just create a ByteArray using that byte[] array and that's what you set the imageData to.

```
        X937ImageViewDataRecord ivdr = 
            (X937ImageViewDataRecord) factory.newX9Record(X9Record. TYPE_IMAGE_VIEW_DATA);
        .
        .
        byte[] image = readImageFromFile(...);
        ivdr.imageData(new ByteArray(image));
        .
```     
The record will be expanded to accommodate the image and the image length will be automatically set to the proper value.

Some other thoughts. All of the records are initialized to the proper standard level and record type, so you don't have to do that. Also the rest of the record is initialized to spaces, so you don't have to set any fields that you want to leave blank, although it does not hurt to do so...

One final note. If you are using maven or gradle to build you software project, these are published on [Maven Central](http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.thelastcheck.commons%22).

If you had not already found the site where the documentation is being created, here it is on [github.io](https://thelastcheck.github.io/#/tlc-open-java). It is just obviously not complete...

I hope this answers your questions. Please let me know if you need more information...

And I'll get to adding the usage notes soon!

Thanks.

**Comment by jerrybowman** [comment]
One other thing you will want to add. There is a filter you can add to the X9 Output Stream that will automatically calculate and update the control records with the proper total counts and amounts so you don't have to do that. Do add this filter, do this:
```
    X9OutputStreamRecordWriter writer = new X9OutputStreamRecordWriter(outputStream);
    writer.addFilter(new ControlTotalsRecordFilter());
```
Now all of your totals will be correct in the output file.

**Comment by leonardolr** [comment]
Hey Jerry! You are awesome! Thank you for the full explanation!!! I'm going to try that tonight!!!

About the maven, yes, I tried to use through maven but I received two issues:
1) In my IDE it's displaying the below error:
![image](https://cloud.githubusercontent.com/assets/6147142/15633926/6c4cfc52-2586-11e6-9cad-7ee09492c7ba.png)

2) And, as I'm using dropwizard, when I try to start the application with the maven dependency I'm receiving this error and my application does not starts:

    Connected to the target VM, address: '127.0.0.1:52800', transport: 'socket'
    SLF4J: Class path contains multiple SLF4J bindings.
    SLF4J: Found binding in [jar:file:/Users/lribeiro/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-log4j12/1.6.1/bd245d6746cdd4e6203e976e21d597a46f115802/slf4j-log4j12-1.6.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
    SLF4J: Found binding in [jar:file:/Users/lribeiro/.gradle/caches/modules-2/files-2.1/ch.qos.logback/logback-classic/1.1.3/d90276fff414f06cb375f2057f6778cd63c6082f/logback-classic-1.1.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
    SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
    SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
    Disconnected from the target VM, address: '127.0.0.1:52800', transport: 'socket'
    Exception in thread "main" java.lang.IllegalStateException: Unable to acquire the logger context
        at io.dropwizard.logging.LoggingUtil.getLoggerContext(LoggingUtil.java:46)
        at io.dropwizard.logging.BootstrapLogging.bootstrap(BootstrapLogging.java:45)
        at io.dropwizard.logging.BootstrapLogging.bootstrap(BootstrapLogging.java:34)
        at io.dropwizard.Application.<init>(Application.java:24)
        at com.myapp.MainApplication.<init>(MainApplication.java:26)
        at com.myapp.MainApplication.main(MainApplication.java:29)

    Process finished with exit code 1

I tried to search how to workaround these issues and the quickest way was to use the source code... And then all the messages goes away and the server starts.

And now with your awesome directions I hope everything will be fine!!!

Thank you very much Jerry! Nice job on this library! 👍

**Comment by jerrybowman** [comment]
It's always good to have someone else use your stuff and see what issues come about. I'll research those errors above and see if I can determine how to fix them. But in the meantime, enjoy and I hope everything works out for you. This library is running in production in a number of systems, so other than figuring out how to use it :-), it should be very stable.

Thanks!

**Comment by leonardolr** [comment]
Thanks Jerry! Everything working pretty cool! I created this upgrade in your docs for the X937 library. I hope it can help you! 

https://github.com/TheLastCheck/thelastcheck.github.io/pull/1
